program: bin/main.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - sweep
  - /app/configs/sweeps/z24/reference/base.yml
  - ${args_json_file}
method: random
metric:
  name: dummy
  goal: minimize
name: z24-reference-sweep
project: z24-reference-gans
parameters:
  model:
    parameters:
      loss:
        values: ["bce", "wasserstein"]
      generator:
        parameters:
          layers:
            values: [[32,64,32], [64, 128, 32]]
          kernel_size:
            values: [3, 5]
          noise_channels:
            values: [2, 4]
          noise_length:
            value: 8
          input_channels:
            value: 2
          output_channels:
            value: 2
          output_size:
            value: 8
          input_size:
            value: 8
      discriminator:
        parameters:
          layers:
            values: [[32, 64, 32], [64, 128, 64]]
          kernel_size:
            values: [3, 5]
          clip_value:
            values: [0.01, 0.05]
          input_channels:
            value: 2
          input_size:
            value: 8
  optimizers:
    parameters:
      discriminator:
        parameters:
          optimizer:
            parameters:
              frequency:
                values: [1, 3, 5]
