dataset:
  base:
    batch_size: 64
    workers: 12
    window_size: 128
    horizon_size: 128
    shuffle: true
    in_memory: True
    mirror: False
  train:
    path: "/data/Z24/assembled-1s.dat"
    ratio: 0.70
  val:
    path: "/data/Z24/assembled-1s.dat"
    shuffle: false
    ratio: 0.05
  test:
    path: "/data/Z24/assembled-1s.dat"
    shuffle: false
    ratio: 0.05
denormalize: true
loss:
  type: "mse"
  reduction: "mean"
  multi_step: True
metrics:
  - "mae"
  - "mape"
  - "rmse"
  - "mse"
optimizers:
  optimizer:
    name: "adam"
    lr: 0.001
    weight_decay: 0
  scheduler:
    name: "exponential"
    gamma: 0.99
trainer:
  devices: 1
  accelerator: "gpu"
  max_epochs: 50
  logger:
    log_model: True
    project: z24-adj-study
  checkpoint:
    metric: "val_TimeSeriesMAE"
    dirpath: "/tmp/checkpoints"
    save_top_k: 3
    filename: "checkpoint-{epoch}-mae-{val_TimeSeriesMAE:.4f}"
  early_stopping:
    metric: "val_TimeSeriesMAE"
    patience: 10
    verbose: True
    delta: 0.0005

