run:
  project: pbim-reference-gans-mean-weighted-random
  entity: ma-thesis-kohlmann
  id: "xh3cg5iq"
  separate: true
  use_best: false
output_path: "/out/pbim/S1/{{NAME}}/"
overrides:
  metrics:
    - precision: {}
    - recall: {}
    - f1: {}
    - accuracy: {}
  dataset:
    base:
      grouping: "pbim"
    test:
      path: "/data/PBIM/S1/merged/anomalous/reference/mean-weighted-random/assembled.dat"
      shuffle: false