dataset:
  base:
    batch_size: 8
    workers: 4
    window_size: 128
    horizon_size: 128
    shuffle: true
    in_memory: True
  train:
    path: "../data/assembled/qgs/A/zzzAU.dat"
  val:
    path: "../data/assembled/qgs/B/zzzBU.dat"
    offset: 0.33
    ratio: 0.33
  test:
    path: "../data/assembled/qgs/B/zzzBU.dat"
    ratio: 0.33
denormalize: true
loss:
  type: "mse"
  reduction: "mean"
  multi_step: True
metrics:
  - "mae"
  - "mape"
  - "rmse"
  - "mse"
optimizers:
  optimizer:
    name: "adam"
    lr: 0.004
    weight_decay: 0
  scheduler:
    name: "exponential"
    gamma: 0.99
trainer:
  devices: "auto"
  accelerator: "cpu"
  max_epochs: 10
  logger:
    log_model: True
    project: "test"
  checkpoint:
    metric: "val_TimeSeriesMAE"
    dirpath: "/tmp/checkpoints"
    save_top_k: 3
    filename: "checkpoint-{epoch}-mae-{val_TimeSeriesMAE:.4f}"
  early_stopping:
    metric: "val_TimeSeriesMAE"
    patience: 3
    verbose: True

