base: "./base.yml"
dataset:
  base:
    horizon_size: 0
    mirror: True
denormalize: False
model:
  type: "tcnae"
  input_size: 30
  input_channels: 1
  output_size: 30
  output_channels: 1
  num_layer: 7
  num_filter: 64
  conv_output_size: 16
  avg_pool_size: 16
  hidden_size: 16
  dropout: 0.2
  kernel_size: 5