base: "./base.yml"
dataset:
  base:
    horizon_size: 0
    mirror: True
model:
  type: "vrae"
  input_size: 30
  input_channels: 1
  output_size: 30
  hidden_dim: 64
  latent_dim: 32
  num_layers: 2
  dropout: 0.1
  block: "GRU"
trainer:
  limit_train_batches: 100
  limit_val_batches: 10
