run:
  project: qgs-agcrn
  entity: ma-thesis-kohlmann
  id: ""
  separate: true
output_path: "/out/qgs/agcrn/eval/mahalanobis"
overrides:
  test_config:
    type: "mahalanobis"
    aggregation: "mean"
    errors: "/out/qgs/agcrn/stats/$ID/errors.npy"
    threshold_fraction: 0.95

  dataset:
    test:
      path: "/data/QGS/anomalous/all/assembled.dat"
  metrics:
    - precision: {}
    - recall: {}
    - f1: {}
    - accuracy: {}
