run:
  project: qgs-tgcn
  entity: ma-thesis-kohlmann
  id: "y6u6y8qp"
  separate: true
output_path: "/out/qgs/tgcn/eval/mae"
overrides:
  test_config:
    type: "mae"
    aggregation: "mean"
    errors: "/out/qgs/tgcn/stats/$ID/errors.npy"
    threshold_fraction: 0.95
  dataset:
    test:
      path: "/data/QGS/anomalous/all/assembled.dat"
  metrics:
    - precision: {}
    - recall: {}
    - f1: {}
    - accuracy: {}
