apiVersion: batch/v1
kind: Job
metadata:
  name: train-{{PREFIX_ESCAPED}}-{{NAME}}{{RUN_NAME_SUFFIX}}
spec:
  backoffLimit: 0
  template:
    spec:
      priorityClassName: research-med
      containers:
        - image: ls6-stud-registry.informatik.uni-wuerzburg.de/studkohlmann-pbim-train:0.1
          name: train-model
          imagePullPolicy: "Always"
          env:
            - name: CONFIG_FILE
              value: "/app/configs/k8s/training/{{PREFIX}}/{{NAME}}.yml"
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb-token
                  key: token
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "16"
              memory: "16Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "12"
              memory: "8Gi"
          command: ["bash", "./scripts/train.sh"]
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /adjacency_matrices
              name: adjacency-matrices
            - mountPath: /checkpoints
              name: checkpoints
            - mountPath: /app/configs
              name: config
            - mountPath: /tmp
              name: tmp
            - mountPath: /.config
              name: tmp
            - mountPath: /.cache
              name: tmp
            - mountPath: /cache
              name: tmp
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /.local
              name: tmp
      imagePullSecrets:
        - name: lsx-registry
      restartPolicy: "Never"
      volumes:
        - name: data
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studkohlmann
            path: "/home/stud/kohlmann/MA/assembled"
            secretRef:
              name: ceph-secret
            readOnly: true
        - name: checkpoints
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studkohlmann
            path: "/home/stud/kohlmann/MA/models/checkpoints"
            secretRef:
              name: ceph-secret
        - name: adjacency-matrices
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studkohlmann
            path: "/home/stud/kohlmann/MA/data/adjacency_matrices"
            secretRef:
              name: ceph-secret
        - name: config
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studkohlmann
            path: "/home/stud/kohlmann/MA/p-bim-models/configs"
            readOnly: true
            secretRef:
              name: ceph-secret
        - name: tmp
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "2Gi"