base: "./base.yml"
model:
  type: "agcrn"
  input_size: 30
  input_channels: 1
  output_channels: 1
  output_size: 30
  num_layers: 3
  node_embedding_dim: 12
  rnn_hidden_dim: 96
  dropout: 0.1
  cheb_k: 2
optimizers:
  optimizer:
    lr: 0.001

