run:
  project: pbim-reference-gans-interpolate-weighted-random
  entity: ma-thesis-kohlmann
  id: [5w87mzq6, 6ttef0oh]
  separate: true
  use_best: false
output_path: "/out/pbim/S3/{{NAME}}/"
overrides:
  metrics:
    - precision: {}
    - recall: {}
    - f1: {}
    - accuracy: {}
  dataset:
    base:
      grouping: "pbim"
    test:
      path: "/data/PBIM/S3/merged/anomalous/reference/interpolate-weighted-random/assembled.dat"
      shuffle: false