run:
  project: pbim-reference-gans-mean-uniform
  entity: ma-thesis-kohlmann
  id: [t01qlqx0, p0s603f6, xqlnbisi]
  separate: true
  use_best: false
output_path: "/out/pbim/S3/{{NAME}}/"
overrides:
  metrics:
    - precision: {}
    - recall: {}
    - f1: {}
    - accuracy: {}
  dataset:
    base:
      grouping: "pbim"
    test:
      path: "/data/PBIM/S3/merged/anomalous/reference/mean-uniform/assembled.dat"
      shuffle: false