run:
  project: pbim-reference-gans-nosampling-uniform
  entity: ma-thesis-kohlmann
  id: "0pfdq68u"
  separate: true
  use_best: false
output_path: "/out/pbim/S3/{{NAME}}/"
overrides:
  metrics:
    - precision: {}
    - recall: {}
    - f1: {}
    - accuracy: {}
  dataset:
    base:
      grouping: "pbim"
    test:
      path: "/data/PBIM/S3/merged/anomalous/reference/nosampling-uniform/assembled.dat"
      shuffle: false